import { Achievement, VocabularyWord } from './types';

export const MOCK_VOCABULARY: VocabularyWord[] = [
  {
    id: '1',
    arabic: 'علم',
    transliteration: '‘ilm',
    meaning: 'Knowledge / Science',
    category: 'Noun',
    status: 'Mastered',
    masteryPercent: 85,
  },
  {
    id: '2',
    arabic: 'قرأ',
    transliteration: 'qara’a',
    meaning: 'To Read',
    category: 'Verb',
    status: 'Learning',
    masteryPercent: 45,
    nextReview: '2 days',
  },
  {
    id: '3',
    arabic: 'طالب',
    transliteration: 'ṭālib',
    meaning: 'Student',
    category: 'Noun',
    status: 'New',
    masteryPercent: 0,
  },
  {
    id: '4',
    arabic: 'كتاب',
    transliteration: 'kitāb',
    meaning: 'Book',
    category: 'Noun',
    status: 'Mastered',
    masteryPercent: 80,
  },
  {
    id: '5',
    arabic: 'ثقافة',
    transliteration: 'thaqāfah',
    meaning: 'Culture',
    category: 'Noun',
    status: 'Learning',
    masteryPercent: 30,
  },
  {
    id: '6',
    arabic: 'مكتبة',
    transliteration: 'maktaba',
    meaning: 'Library',
    category: 'Academic',
    status: 'Learning',
    masteryPercent: 80,
  },
  {
    id: '7',
    arabic: 'بحث',
    transliteration: 'baḥth',
    meaning: 'Research',
    category: 'Scholarly',
    status: 'Learning',
    masteryPercent: 60,
  },
  {
    id: '8',
    arabic: 'جامعة',
    transliteration: 'jāmi‘a',
    meaning: 'University',
    category: 'Academic',
    status: 'Mastered',
    masteryPercent: 100,
  }
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: '1',
    title: 'Lexicographer',
    description: '500 Words Mastered',
    icon: 'Award',
    status: 'unlocked',
    color: 'bg-tertiary-fixed',
  },
  {
    id: '2',
    title: 'Early Bird',
    description: '10 Sessions before 8 AM',
    icon: 'BookOpen',
    status: 'unlocked',
    color: 'bg-primary-fixed',
  },
  {
    id: '3',
    title: 'Polyglot Path',
    description: 'Complete 5 Modules',
    icon: 'Lock',
    status: 'locked',
    color: 'bg-surface-variant',
  },
  {
    id: '4',
    title: 'Calligrapher',
    description: '65/100 roots',
    icon: 'History',
    status: 'in-progress',
    progress: 65,
    color: 'bg-secondary-fixed',
  },
];
